on: push
jobs:
  first_job:
    name: check-out-repo
    runs-on: ubuntu-latest
    steps:
        - name: check repo
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.CR_PAT }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/alpine-extended:latest